/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#e10600",
        "on-tertiary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474646",
        "surface-variant": "#353534",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary-fixed": "#1c1b1b",
        "surface-dim": "#131313",
        "inverse-on-surface": "#313030",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "on-primary-fixed": "#410100",
        "tertiary-container": "#717070",
        "primary": "#ffb4a8",
        "primary-fixed": "#ffdad4",
        "secondary": "#c8c6c5",
        "secondary-container": "#4a4949",
        "outline": "#af8781",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "tertiary": "#c8c6c5",
        "background": "#0a0a0a",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#5e3f3a",
        "inverse-primary": "#c00500",
        "on-secondary": "#313030",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#474746",
        "on-tertiary": "#313030",
        "primary-fixed-dim": "#ffb4a8",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary-container": "#fff2f0",
        "surface": "#131313",
        "on-primary-fixed-variant": "#930300",
        "surface-container": "#201f1f",
        "on-tertiary-container": "#f8f5f4",
        "surface-tint": "#ffb4a8",
        "on-primary": "#680200",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#e9bcb5",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#bab8b7",
        "surface-bright": "#3a3939",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface-container-highest": "#353534"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "mobile_margin": "12px",
        "container_gap": "16px",
        "desktop_margin": "24px",
        "navbar_height": "48px",
        "sidebar_width": "240px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "mono-data": ["13px", { "lineHeight": "1", "fontWeight": "500" }],
        "display-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
