/** @type {import('tailwindcss').Config} */
// "Apex Velocity" design system — see new ui/stitch_pitwall_strategy_platform/apex_velocity/DESIGN.md
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f20",
        "on-tertiary-fixed-variant": "#003ea7",
        "surface-dim": "#131314",
        "on-surface": "#e5e2e3",
        "background-base": "#0a0a0b",
        "on-tertiary-fixed": "#00174a",
        "status-go": "#00d21d",
        "on-primary": "#680200",
        "secondary-fixed": "#e5e2e1",
        "f1-red": "#e10600",
        "on-primary-fixed-variant": "#930300",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353436",
        "error": "#ffb4ab",
        "surface-tint": "#ffb4a8",
        "tertiary-container": "#0163ff",
        "tertiary-fixed": "#dbe1ff",
        "secondary": "#c8c6c5",
        "primary-fixed-dim": "#ffb4a8",
        "inverse-primary": "#c00500",
        "on-primary-fixed": "#410100",
        "outline": "#af8781",
        "status-caution": "#fffb00",
        "surface-bright": "#3a393a",
        "on-primary-container": "#fff2f0",
        "primary": "#ffb4a8",
        "on-tertiary-container": "#f4f4ff",
        "on-background": "#e5e2e3",
        "inverse-surface": "#e5e2e3",
        "background": "#131314",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-high": "#2a2a2b",
        "on-secondary-fixed-variant": "#474746",
        "background-surface-elevated": "#1c1c1c",
        "on-secondary-container": "#b7b5b4",
        "outline-variant": "#5e3f3a",
        "on-surface-variant": "#e9bcb5",
        "border-rim": "rgba(255, 255, 255, 0.08)",
        "f1-red-hover": "#e8001d",
        "glass-overlay": "rgba(16, 16, 18, 0.7)",
        "on-secondary-fixed": "#1b1b1b",
        "primary-container": "#e10600",
        "on-secondary": "#313030",
        "primary-fixed": "#ffdad4",
        "inverse-on-surface": "#313031",
        "surface-container-low": "#1c1b1c",
        "tertiary": "#b4c5ff",
        "surface-container-highest": "#353436",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-error": "#690005",
        "background-surface": "#111114",
        "on-tertiary": "#002a77",
        "surface-container-lowest": "#0e0e0f",
        "surface": "#131314",
        "status-stop": "#ff1801",
        "secondary-container": "#474746"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sidebar-width": "240px",
        "topbar-height": "48px",
        "margin-mobile": "16px",
        "base": "8px",
        "gutter": "16px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "telemetry-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "telemetry-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "telemetry-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"]
      }
    }
  },
  plugins: [],
}
